"""empty message

Revision ID: 034fdb71ebbf
Revises: 
Create Date: 2022-05-31 10:04:45.822508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034fdb71ebbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todo SET completed=False WHERE completed IS NULL;')

    op.alter_column('todo', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
